### ISSUE TITLE
希望能多点ACM的资料

### ISSUE THREAD

**Issue by Aneureka** [NJU-SE-15-share-review/professional-class#2]
# 然后那个sam博客链接挂了...

**Comment by WaterWan** [comment]
@4thcalabash ACM的内容主要是这位同学负责提供的，如有意向可以跟他说一说。

**Comment by WaterWan** [comment]
对于sam博客挂了这件事， @4thcalabash 建议你试一下科学上网

**Comment by Aneureka** [comment]
唔，平常都挂着ss，开了全局也访问不了他的博客..
