### ISSUE TITLE
资料里的图好像全都看不见…

### ISSUE THREAD

**Issue by pujx233** [NJU-SE-15-share-review/professional-class#23]
pdf下载下来也是打不开

**Comment by Prevalence** [comment]
你得说明具体哪份pdf有问题

**Comment by pujx233** [comment]
> 你得说明具体哪份pdf有问题

所有的pdf文件下载下来都显示"无法打开'xx.pdf"文件，因为它不是支持的文件类型或因为文件已经损坏。"

**Comment by Prevalence** [comment]
> > 你得说明具体哪份pdf有问题
> 
> 所有的pdf文件下载下来都显示"无法打开'xx.pdf"文件，因为它不是支持的文件类型或因为文件已经损坏。"

我尝试了web的名词解释这份pdf和操作系统的答案汇总pdf，下载打开没有问题。并且网页上也能成功预览

**Comment by Prevalence** [comment]
你可以确认一下你有没有安装git-lfs
