### ISSUE TITLE
请问有软工一的考卷资料嘛

### ISSUE THREAD

**Issue by NJUgfy** [NJU-SE-15-share-review/professional-class#4]
_(:з」∠)_

**Comment by frostwing98** [comment]
十分抱歉，软工一的考卷资料目前还没有。而且刘钦老师每年的考题都完全不同。但是总体来说，尽管考题很新，但是难度并不太大。

**Comment by g461640437** [comment]
已添加部分回忆内容，希望帮的上忙。

**Comment by frostwing98** [comment]
新的内容（包括学习总结、建议以及回忆版考题）已被添加入Repository，学弟学妹们如有疑问可以戳上面的 @g461640437 学长。
